<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>

<div id="fb-root"></div>
<script type="text/javascript">(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-comments" data-href="<?php
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Loke\FBC\Block\FBC');
if ($currentProduct = $myBlock->getCurrentProduct()) {
        echo $currentProduct->getProductUrl();
} ?>" data-numposts="5" data-width="100%"></div>